### ISSUE TITLE
HELP!  need to run on a phone 

### ISSUE THREAD

**Issue by perfecten** [Luuka/GPXParser.js#16]
I need to run on a phone app(ios/android).
but i get a error about "window.DOMParser".

**Comment by Luuka** [comment]
Hello,

Where does your app run ? in a webview ?

The DOMParser is an embedded functionnality of standard web browsers but is not present in all js-based environment. To fix that in a node.js context I require `jsdom-global` (see https://github.com/Luuka/GPXParser.js/blob/master/src/GPXParser.js#L404)

If you installed GPXParser from npm it should work, otherwise you can install and require `jsdom-global` by yourself.

**Comment by perfecten** [comment]
Thanks for your answer.
My app is a apk, a react-native project , does not run in a webview.

I installed  GPXParser from npm  .

**Comment by aliciasteiman** [comment]
did you ever resolve this? having the same issue...

**Comment by perfecten** [comment]
@aliciasteiman 
I gived up.
and I had used react-native-xml2js.
